### ISSUE TITLE
code sharing

### ISSUE THREAD

**Issue by Raven24** [SuperTux88/diaspora_federation#1]
hey, I think it's great you started implementing some actual code to finally make federation better! :)

Just one thought that crossed my mind: would you be open to using my gem in your engine instead of copying the code you need? 
I had this idea to provide the gem as a library to any other (not necessarily rails-based) Ruby project that might want to implement our protocol in some way. You could also say it provides the "business logic" and your rails engine would simply tie it to a specific framework.

Anyway, this week my university holidays are starting, so if you'd like to collaborate, just let me know what you have in mind (I never really had anything to do with a rails engine before...)

**Comment by SuperTux88** [comment]
I'm not sure, if it's a good idea to split the federation into two gems. I have also refactored some part of your code and I'm more flexible if i copy the parts i need.

I have done some federation work in the 0.5.1.0 release and most of the bugs are not in the parts that you have extracted to your gem. So I wanted to have most of the federation logic in this gem and not only the xml generation/parsing.

I think it's still possible to use this gem without Rails, but you need to do the stuff I had done in the controllers by your own (but I have not tested that yet).

I think it is better to have all federation stuff at one place, so you don't need to edit two gems if you extend the federation.

If you want to collaborate I can give you write access to this repo and we can do this together. :)

**Comment by SuperTux88** [comment]
Maybe we can use something like this: http://opensoul.org/2012/05/30/releasing-multiple-gems-from-one-repository/ to release a gem without the rails dependency and without the controllers. So we can have all files in one repo, but have two gems with the same version that work together. What do you think about this idea?

**Comment by Raven24** [comment]
you're right, it would make development a bit annoying, having to touch two repos every time.
I like the multi-gem approach. that seems to really get the best of both approaches :)
I will look at your code and the PR on the main repo im more detail later today.

**Comment by jaywink** [comment]
Is it really a good idea to go for two gems? What would be the advantage in a situation where an application needs to implement diaspora federation?

Also, I'd not make things too fancy because IMHO the most important thing is to get the federation bits *out* of diaspora. This means diaspora could possibly switch or at least support some other protocol in the future - which would kinda make this or these gems redundant ;)

**Comment by SuperTux88** [comment]
Yes, and the federation doesn't work without some routes...

But if @Raven24 wants a gem without the rails-stuff I can try to add a second build. Then we can generate a second gem with small additional work. But I want to have everything in the same repo.

**Comment by Raven24** [comment]
Yeah, true. I'm just thinking about a possible alternative implementation, maybe using sinatra or a different web framework that doesn't have anything to do with rails.
also I had the "layered" approach in mind, where there would be a library providing the basic functionality and a layer on top of that providing the binding to rails controllers/models. that would make testing more straightforward, since you'd be able to test agains well-defined interfaces instead of private internals or implementation quirks.

**Comment by SuperTux88** [comment]
@Raven24: there is a gem without rails now. :) Is this ok for you?

**Comment by Raven24** [comment]
looks good, I'm happy ;)
