### ISSUE TITLE
Making a 0.0.9 release

### ISSUE THREAD

**Issue by cmrd-senya** [SuperTux88/diaspora_federation#15]
Looks like the functionality is now enough for me to finish tests at [6539](https://github.com/diaspora/diaspora/pull/6539). I want it to be merged to Diaspora and this will definitely require to rely on a release version of the diaspora_federation gem. So, can we form TODOs required for a new (though minor) release?

**Comment by SuperTux88** [comment]
The main-TODO is to add documentation to all new entities and validators.

Currently this looks like this:
```
Modules:        14 (    3 undocumented)
Classes:        84 (   35 undocumented)
Constants:      22 (    0 undocumented)
Methods:       139 (    6 undocumented)
 83.01% documented
```

You can see this when you run `yardoc --list-undoc`.

**Comment by cmrd-senya** [comment]
So can we release 0.0.9 now?
@jhass, since it is a blocker for the [6539](https://github.com/diaspora/diaspora/pull/6539) I think it would be nice if you confirm it is ok and won't require any changes in the gem to merge the PR.

**Comment by SuperTux88** [comment]
I want to have a look at the gem and maybe do some cleanups today or tomorrow, but then I can build a release.

**Comment by cmrd-senya** [comment]
I think you'll merge salmon to master right? salmon was our development branch, so we'll need a new one then with a more straight name.

**Comment by SuperTux88** [comment]
yes, I'll create a `develop` branch after that. `salmon` was my feature-branch as I was working alone at this ;)

**Comment by cmrd-senya** [comment]
@SuperTux88, I just thought that the next thing I would need are retractions and they have to support signatures as well in the gem. I think that I want to see them in the release too. So how about setting this as a blocker for the release?

**Comment by SuperTux88** [comment]
Add whatever you need and then say me when you need a release :)

**Comment by SuperTux88** [comment]
just for your information: I moved the `salmon` branch to `develop` and made it the default branch.

**Comment by cmrd-senya** [comment]
I think time for the release has come

**Comment by SuperTux88** [comment]
I'll do the release at the weekend.

**Comment by SuperTux88** [comment]
I just released 0.0.9: https://rubygems.org/gems/diaspora_federation

**Comment by cmrd-senya** [comment]
Thanks!

**Comment by Flaburgan** [comment]
Awesome guys :)

I'm wondering, you are using semver here, why do you increment the hotfix number instead of the minor one?

**Comment by cmrd-senya** [comment]
According to semver numeration must start with 0.1.0, so we have to
release 0.1.0 next to become accordant.
