### ISSUE TITLE
Allow to change Faraday settings for the gem user

### ISSUE THREAD

**Issue by cmrd-senya** [SuperTux88/diaspora_federation#7]
The user might want to change the defaults provided in [lib/diaspora_federation/fetcher.rb](https://github.com/SuperTux88/diaspora_federation/blob/master/lib/diaspora_federation/fetcher.rb).

Diaspora has the following initialization for Faraday: https://github.com/diaspora/diaspora/blob/develop/config/initializers/faraday.rb#L6

It sets Faraday.default_adapter to Typhoeus only when run in non-test mode, because Typhoeus requests are badly caught by WebMock. When we utilize diaspora_federation from the Diaspora's test suite we want a similar behavior from the gem. So we want a way to configure this at the configuration time.

**Comment by SuperTux88** [comment]
I use the `Faraday.default_adapter`, so this should work now.

**Comment by cmrd-senya** [comment]
It looks like it works for me, thanks!
